import type { Metadata } from "next"
import "./globals.css"
import { Nunito } from "next/font/google"
import Footer from "./_components/footer"
import { Toaster } from "./_components/ui/sonner"
import AuthProvider from "./_providers/auth"

export const metadata: Metadata = {
  title: "Project Barber",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
}

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={nunito.className}>
        <AuthProvider>
          {children}
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
